version: '3.8'

services:
  # PHP Apache Web Server
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fourjs-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=fourjs_db
      - DB_USER=fourjs_user
      - DB_PASS=fourjs_password
    networks:
      - fourjs-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: fourjs-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fourjs_db
      MYSQL_USER: fourjs_user
      MYSQL_PASSWORD: fourjs_password
      MYSQL_ROOT_PASSWORD: root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fourjs-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fourjs-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - fourjs-network

networks:
  fourjs-network:
    driver: bridge

volumes:
  dbdata: